---
- hosts: all
  become: yes
  tasks:

    - name: update centos server
      tags: always
      package:

          update_only: yes
          update_cache: yes
      when: ansible_distribution == "CentOS"

    - name: Inastall apache in centos server
      tags: apache, httpd, CentOS
      package:
          name: 
              - httpd
          state: latest
          update_cache: yes
      when: ansible_distribution == "CentOS"
