---
- hosts: all
  become: yes
  pre_tasks:

    - name: update centos server
      tags: always
      package:

          update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: update Ubuntu Server
      tags: always
      package:

          update_cache: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu"

- hosts: demo
  become: yes
  roles:
    - demo

- hosts: workstation
  become: yes
  roles:
    - workstation
